#!/bin/bash

prg=$0

# Check if symbolic link
while [ -h "$prg" ] ; do
    ls=$(ls -ld "$prg")
    link=$(expr "$ls" : '.*-> \(.*\)$')
    if expr "$link" : '.*/.*' > /dev/null; then
        prg="$link"
    else
        prg="$(dirname "$prg")/$link"
    fi
done

shell_path=$(dirname "$prg")
absolute=$(echo "$shell_path" | grep "^/")

if [ -z "$absolute" ]; then
    export QUALIMAP_HOME="$(pwd)/$shell_path"
else
    export QUALIMAP_HOME="$shell_path"
fi

JAVA_OPTS="-Xms32m -Xmx1G"

# Path to the JAR file and lib directory using QUALIMAP_HOME
QUALIMAP_JAR="$QUALIMAP_HOME/qualimap.jar"
LIB_DIR="$QUALIMAP_HOME/lib"

# Main class to run
MAIN_CLASS="org.bioinfo.ngs.qc.qualimap.main.NgsSmartMain"

# Check if QUALIMAP_JAR and LIB_DIR exist
if [ ! -f "$QUALIMAP_JAR" ]; then
    echo "Error: $QUALIMAP_JAR not found!"
    exit 1
fi

if [ ! -d "$LIB_DIR" ]; then
    echo "Error: $LIB_DIR directory not found!"
    exit 1
fi

# Run the Java application with Java 17
java $JAVA_OPTS -cp "$QUALIMAP_JAR:$LIB_DIR/*" $MAIN_CLASS "$@"
